### ISSUE TITLE
Spam prevention

### ISSUE THREAD

**Issue by zethra** [RITlug/teleirc#364] opened 2021-01-12 03:09 UTC
# Summary

Help prevent spam messages from getting forwarded to IRC. 

# Background

**Is your feature request related to a problem? Please describe**:
We've been getting a lot of spam messages in #rit-foss recently from the telegram end. The captcha bot deleted the spam messages on the telegram end but they still end up in IRC. 

**Describe the solution you'd like**:
A solution proposed by Repkam09 was to have teleirc not forward a user's messages until they complete the captcha. 

**Describe alternatives you've considered**:
Alternatively, teleirc could hold back messages from new users for a short time and drop them if the user leaves. 

# Details

I'm not familiar with the workings or teleirc so I don't know how viable these suggestions are. I imagine the second one would be easier since it wouldn't require Integration with another bot. 

# Outcome

Reduce spam in IRC.

**Comment by Tjzabel** [comment] 2021-01-23 19:53
Hmm... This is definitely a hard issue to solve. We can try to look at message metadata on Telegram's side and see if there is a way to tell if a user has completed the captcha or not. 

The second alternative seems a bit iffy to me, since a new user coming into the TG group would want assistance, and be confused as to why they are being ignored if they join in the middle of a conversation. I feel it could possibly work if we have like a 5 minute timer to when a message can be sent into the channel. So basically: 

1. check if a user has joined more than 5 mins ago
2. If this is not the case, go in a loop and wait until the statement is true. 
3. At that point, make sure the user is still in the TG group, and then send the message.

**Comment by jwflory** [comment] 2021-11-22 00:25
Looking through the issue backlog, this is a duplicate of issue #327. Closing this issue in favor of unifying the discussion there.

**Closed** 2021-11-22 00:25 UTC
Labels: new change, needs triage
