### ISSUE TITLE
multi-line messages should have each lined prefixed with the userid

### ISSUE THREAD

**Issue by bexelbie** [RITlug/teleirc#95] opened 2018-11-28 18:05 UTC
This will make the messages easier to understand on the irc side.

**Comment by Tjzabel** [comment] 2018-11-28 18:41
@bexelbie I agree! This should be relatively simple to implement.

**Comment by jwflory** [comment] 2018-11-28 22:45
Closing as a duplicate of #53. By the looks of it, @michalrud actually took a crack at it already, but I'm not sure if he is still working on it.

I'm going to steal the name of this issue and rename the other one, since I think this issue title is more clear.

**Closed by jwflory** 2018-11-28 22:45 UTC
Labels: enhancement, priority:med
