### ISSUE TITLE
Requires super-new glibc -- will not run on Debian

### ISSUE THREAD

**Issue by romanrm** [RITlug/teleirc#363] opened 2021-01-06 09:19 UTC
Hello,

I'm not sure what's the target platform for the precompiled release, but unfortunately it will not run on any currently existing version of Debian.

./teleirc-2.1.0-linux-x86_64: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by ./teleirc-2.1.0-linux-x86_64)

As you can see 2.32 is not even in the newest unstable and experimental yet at the moment: https://packages.debian.org/search?keywords=libc-bin (only 2.31). And the current stable release ships version 2.28.

Is there any practical requirement to depend on glibc 2.32? Otherwise doesn't seem great to exclude a huge portion of users for no particular reason.

**Comment by Tjzabel** [comment] 2021-01-23 19:44
Ah, I figured we may run into issues with this. We are currently still trying to figure out the best way to use precompiled binaries to distribute TeleIRC easily. 

A workaround for this is to download or clone TeleIRC, and run `go build cmd/teleirc.go`. That will build a TeleIRC binary for your own system/architecture.

**Comment by Tjzabel** [comment] 2021-07-21 20:27
Hello, is this issue still the case?

**Comment by jwflory** [comment] 2021-11-22 00:20
I'm tempted to say we close this as a duplicate of #343, since the release automation would hypothetically solve this.

**Comment by Tjzabel** [comment] 2022-01-31 21:51
Going to close this issue as a duplicate and unsolved. There are no immediate actionable tasks for this issue.

**Closed by Tjzabel** 2022-01-31 21:51 UTC
Labels: bug, wontfix
