### ISSUE TITLE
Is there support for IRC server password?

### ISSUE THREAD

**Issue by SLKTH** [RITlug/teleirc#172] opened 2019-09-15 10:42 UTC
I have a password set up to connect my IRC server. Is there an option to configure this in the .env file?

**Comment by Tjzabel** [comment] 2019-09-15 16:41
Hmm... At the moment we do not support channels that require password authentication.

I looked into whether or not the IRC library we use supports this, and I'm not sure they do. I followed up with them to ask for clarification, and will let you know when I find out.

Thanks for the issue :+1:

**Comment by Tjzabel** [comment] 2019-09-15 16:48
I am actually going to mark this issue as a duplicate of #129 

My response is the same, in that we are looking to see if this is viable to do. Further development on this topic will be focused in the issue listed above.

**Comment by SLKTH** [comment] 2019-09-16 00:37
> I am actually going to mark this issue as a duplicate of #129
> 
> My response is the same, in that we are looking to see if this is viable to do. Further development on this topic will be focused in the issue listed above.

To be precise, I'm not talking about a password for accessing an specific IRC channel but rather the whole server itself upon connecting. 

I see the two as seperate things although the workings behind it might be the same. 

Thanks for looking into this.

**Comment by Tjzabel** [comment] 2019-09-16 01:15
@SLKTH woops! Thanks for the clarification. While the two issues are in the same vein, they are clearly distinct.

This issue seems simple enough, but I expect this issue will sadly not be taken care of for the time being, as we have just started our next grouping of sprints. We are currently on a feature freeze as we [port TeleIRC to Go](https://github.com/RITlug/teleirc/issues/163). Feel free to [follow here](https://github.com/RITlug/teleirc/projects/1?fullscreen=true) with what we are currently working on. 

I will label this issue as low hanging fruit in case someone else wishes to pick up this issue.

**Comment by HolmesSherlock** [comment] 2019-09-24 05:24
Will stay tuned for the server password support!

**Comment by HolmesSherlock** [comment] 2019-09-24 05:43
[This](https://node-irc.readthedocs.org/en/latest/API.html#client) might be relevant.

**Comment by Tjzabel** [comment] 2019-09-26 18:01
@SLKTH PR #186 should cover this issue.

**Closed** 2019-09-30 01:26 UTC
Labels: good first issue, help wanted, question

**Comment by Tjzabel** [comment] 2019-09-30 01:50
@SLKTH TeleIRC v1.3.3 has been released to support channel keys and server passwords.

Please let me know if the latest release doesn't fix your issues!
