### ISSUE TITLE
Error Bad Request: chat not found

### ISSUE THREAD

**Issue by steliosmilidonis** [RITlug/teleirc#353] opened 2020-10-26 19:10 UTC
# Summary

When attempting to start teleirc i am getting the following

INFO: 2020/10/26 19:05:18 Current TeleIRC version: 
INFO: 2020/10/26 19:05:18 Creating new Telegram bot client...
INFO: 2020/10/26 19:05:18 Creating new IRC bot client...
INFO: 2020/10/26 19:05:18 Starting up Telegram bot...
INFO: 2020/10/26 19:05:18 Starting up IRC bot...
INFO: 2020/10/26 19:05:18 Authorized on account cool_dev_bot
ERROR: 2020/10/26 19:05:28 Bad Request: chat not found
ERROR: 2020/10/26 19:05:28 Bad Request: chat not found
ERROR: 2020/10/26 19:05:28 Bad Request: chat not found
ERROR: 2020/10/26 19:05:28 EOF
ERROR: 2020/10/26 19:05:28 EOF
INFO: 2020/10/26 19:05:28 Shutting Down...
INFO: 2020/10/26 19:05:28 Exiting

**Comment by jwflory** [comment] 2020-10-27 13:18
@steliosmilidonis This looks like an error from the Telegram API. It looks like the `TELEGRAM_CHAT_ID` you have is incorrect or does not exist. This is why you are getting a bad request, because Telegram cannot find any chat room with that chat ID.

Are you able to double-check or confirm another way whether you have the right chat room ID?

**Comment by jwflory** [comment] 2020-10-29 02:22
@steliosmilidonis I will keep this issue open until our next developer sprint this Sunday. Please let us know if you were able to figure out the issue. 🙂

**Comment by jwflory** [comment] 2020-11-01 17:03
Following up, we didn't hear anything back by the developer meeting, and we cannot reproduce on our side. I am closing this issue as `needs info`.

**Closed by jwflory** 2020-11-01 17:03 UTC
Labels: bug, needs info
